# Generated by Django 5.1.3 on 2025-02-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_product_base_unit_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='public_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
