# Generated by Django 5.1.3 on 2025-02-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_productunit_public_price_productunit_supplier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
