# Generated by Django 5.1.3 on 2025-11-18 00:13

import django.db.models.deletion
from django.db import migrations, models


def create_default_statuses(apps, schema_editor):
    Status = apps.get_model('inventario', 'status')
    # Intentar crear con ids explícitos; si id=0 falla en tu BD, se seguirá intentando por nombre
    for pk, name in [(0, 'inactivo'), (1, 'activo')]:
        try:
            Status.objects.update_or_create(id=pk, defaults={'name': name})
        except Exception:
            Status.objects.update_or_create(name=name)


def remove_default_statuses(apps, schema_editor):
    Status = apps.get_model('inventario', 'status')
    Status.objects.filter(name__in=['inactivo', 'activo']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_productvariant_product_productvariant_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        # crear los registros antes de añadir las FK que usan default=1
        migrations.RunPython(create_default_statuses, reverse_code=remove_default_statuses),
        migrations.AddField(
            model_name='productunit',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.status'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.status'),
        ),
        migrations.AddField(
            model_name='stockunit',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.status'),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.status'),
        ),
    ]
