# Generated by Django 5.1.3 on 2025-02-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='url_instancia',
        ),
    ]
